name: flutter_application_1
description: "A new Flutter project."
# A linha seguinte previne que o pacote seja acidentalmente publicado no
# pub.dev usando `flutter pub publish`. Isso é preferível para pacotes privados.
publish_to: 'none' # Remova esta linha se desejar publicar no pub.dev

# A seguinte define a versão e o número de build para sua aplicação.
# Um número de versão é três números separados por pontos, como 1.2.43,
# seguido de um número de build opcional separado por um +.
# Ambos a versão e o número de build podem ser substituídos em flutter
# build especificando --build-name e --build-number, respectivamente.
# No Android, build-name é usado como versionName enquanto build-number é usado como versionCode.
# Leia mais sobre versionamento no Android em https://developer.android.com/studio/publish/versioning
# No iOS, build-name é usado como CFBundleShortVersionString enquanto build-number é usado como CFBundleVersion.
# Leia mais sobre versionamento no iOS em
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# No Windows, build-name é usado como as partes major, minor e patch
# das versões do produto e do arquivo enquanto build-number é usado como sufixo de build.
version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3  # Adicionando a dependência para realizar solicitações HTTP
  cupertino_icons: ^1.0.6
  shared_preferences: ^2.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
