<<<<<<< HEAD
version: "3.9"

services:
  mongo:
    image: mongo
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: "admin"
      MONGO_INITDB_ROOT_PASSWORD: "pass2022"
=======
version: "3.9"

services:
  mongo:
    image: mongo
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: "admin"
      MONGO_INITDB_ROOT_PASSWORD: "pass2022"
>>>>>>> 26bf485aca5dc1ee27b862a9623ba1ee4055739d
